DROP DATABASE IF EXISTS Creative_Db;

CREATE DATABASE Creative_Db;
USE Creative_Db;

CREATE TABLE Country (
	countryID INT PRIMARY KEY AUTO_INCREMENT,
	country_code VARCHAR(10),
    country_name VARCHAR(20)
);

CREATE TABLE `Field`(
	fieldID INT PRIMARY KEY AUTO_INCREMENT,
    field_name VARCHAR(10) UNIQUE NOT NULL,
    field_description VARCHAR(100)
);

-- UNIQUE NOT NULL
CREATE TABLE Users ( 
	userID INT PRIMARY KEY AUTO_INCREMENT, 
	phone_number VARCHAR(20), 
	email VARCHAR(30), 
	address VARCHAR(50), 
	image BLOB, 
	passcode VARCHAR(255), 
	account_number INT, 
	countryID INT, 
	date_joined DATE, 
    isAdmin BOOLEAN,
	fieldID INT,
    FOREIGN KEY (countryID) REFERENCES Country(countryID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (fieldID) REFERENCES `Field`(fieldID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Artist(
	artistID INT PRIMARY KEY, 
    website VARCHAR(30),
    FOREIGN KEY (artistID) REFERENCES Users(userID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Individual_Artist(
	artistID INT PRIMARY KEY,
    website VARCHAR(30),
    f_name VARCHAR(10),
    l_name VARCHAR(10),
    signature_name VARCHAR(10) UNIQUE,
    gender VARCHAR(10) NOT NULL,
    date_of_date DATE NOT NULL,
    FOREIGN KEY (artistID) REFERENCES Artist(artistID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Company_Artist(
	artistID INT PRIMARY KEY, 
    company_name VARCHAR(20) NOT NULL, 
    date_of_setup DATE, 
    company_description VARCHAR(100),
    FOREIGN KEY (artistID) REFERENCES Artist(artistID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Visitor(
	visitorID INT PRIMARY KEY,
    FOREIGN KEY (visitorID) REFERENCES Users(userID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Individual_Visitor(
	visitorID INT PRIMARY KEY,
	f_name VARCHAR(10), 
    l_name VARCHAR(10), 
    gender VARCHAR(10) NOT NULL, 
    date_of_birth DATE NOT NULL,
    FOREIGN KEY (visitorID) REFERENCES Visitor(visitorID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Company_Visitor(
	visitorID INT PRIMARY KEY,
	company_name VARCHAR(20) NOT NULL, 
    company_description VARCHAR(100),
    FOREIGN KEY (visitorID) REFERENCES Visitor(visitorID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE News(
	newsID INT PRIMARY KEY AUTO_INCREMENT,
    fieldID INT,
    date_posted DATE,
    tags VARCHAR(50),
    news_description VARCHAR(200),
	image BLOB,
    FOREIGN KEY (fieldID) REFERENCES `Field`(fieldID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Artwork (
	artworkID INT PRIMARY KEY AUTO_INCREMENT,
	artworkTitle VARCHAR(50),
	artistID INT,
	fieldID INT,
	artworkDescription VARCHAR(100),
	quantity INT,
	price FLOAT, 
	dateCreated DATE,
    `status` BOOLEAN,
	FOREIGN KEY (fieldID) REFERENCES `Field`(fieldID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (artistID) REFERENCES Artist(artistID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Image (
	imageID INT PRIMARY KEY,
	image BLOB,
	FOREIGN KEY (imageID) REFERENCES Artwork(artworkID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Link (
	linkID INT,
	link VARCHAR(100),
	FOREIGN KEY (linkID) REFERENCES Artwork(artworkID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `Text` (
	textID INT,
	textContent TEXT,
	FOREIGN KEY (textID) REFERENCES Artwork(artworkID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE UserPurchase (
	orderID INT PRIMARY KEY AUTO_INCREMENT,
	artworkID INT,
	customerID INT,
	datePurchased DATETIME,
	FOREIGN KEY (artworkID) REFERENCES Artwork(artworkID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (customerID) REFERENCES Users(userID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `Comment` (
	commentID INT PRIMARY KEY AUTO_INCREMENT,
	artworkID INT,
	userID INT,
	datePosted DATETIME,
	commentMessage VARCHAR(50),
	FOREIGN KEY (artworkID) REFERENCES Artwork(artworkID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (userID) REFERENCES Users(userID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CommentLike (
	commentID INT,
	userID INT,
	dateLiked DATETIME,
	FOREIGN KEY (commentID) REFERENCES `Comment`(commentID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (userID) REFERENCES Users(userID) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY (commentID, userID)
);

CREATE TABLE `Like` (
	artworkID INT,
	userID INT,
	dateLiked DATETIME,
	FOREIGN KEY (artworkID) REFERENCES Artwork(artworkID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (userID) REFERENCES Users(userID) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY (artworkID, userID)
);

CREATE TABLE ArtistSubscriber (
	artistID INT,
	userID INT,
	dateSubscribed DATETIME,
	FOREIGN KEY (artistID) REFERENCES Artist(artistID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (userID) REFERENCES Users(userID) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY (artistID, userID)
);

CREATE TABLE UserField (
	artistID INT,
	fieldID INT,
	FOREIGN KEY (artistID) REFERENCES Artist(artistID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (fieldID) REFERENCES `Field`(fieldID) ON DELETE CASCADE ON UPDATE CASCADE
);

